# Generated by Django 5.0 on 2024-11-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='shoppost',
            name='image1',
        ),
        migrations.AddField(
            model_name='shoppost',
            name='day',
            field=models.CharField(default=' ', max_length=10, verbose_name='教科'),
        ),
        migrations.AddField(
            model_name='shoppost',
            name='price',
            field=models.CharField(default=' ', max_length=10, verbose_name='点数'),
        ),
        migrations.AlterField(
            model_name='shoppost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.category', verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='shoppost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='shoppost',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.condition'),
        ),
    ]
